supergraph:
  path: /graphql
  introspection: true
homepage:
  enabled: false
sandbox:
  enabled: true
cors:
  origins:
    - http://localhost:3000
    - http://localhost:4200
    - http://localhost:4201
    - http://localhost:4202
    - https://studio.apollographql.com
  allow_credentials: true
include_subgraph_errors:
  all: true
headers:
  all:
    request:
      - propagate:
          named: "authorization"
      - propagate:
          named: "cookie"
