federation_version: 2
subgraphs:
  catalog:
    routing_url: http://localhost:4001/
    schema:
      subgraph_url: http://localhost:4001/
  checkout:
    routing_url: http://localhost:4002/
    schema:
      subgraph_url: http://localhost:4002/
  customer:
    routing_url: http://localhost:4003/
    schema:
      subgraph_url: http://localhost:4003/
  wishlist:
    routing_url: http://localhost:4004/
    schema:
      subgraph_url: http://localhost:4004/
